#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Muscle meshing
cd muscle/                                                      # move to muscle folder
cleanCase
runApplication blockMesh                          # base mesh for muscle region
runApplication snappyHexMesh -overwrite               # snappy hex mesh to chisel into curved shape

# TUMOR MESHING 
cd ../tumor/                                                    # move to tumor folder
cleanCase
runApplication blockMesh                          # base mesh for tumor region
runApplication pyFoamFromTemplate.py system/snappyHexMeshDict "{'x':0, 'y':0.035, 'z':0, 'r':0.005}"
runApplication snappyHexMesh -overwrite               # snappy hex mesh to chisel into curved shape

# TISSUE MESHING 
cd ../tissue/                                                   # move to tissue folder
cleanCase
runApplication blockMesh                          # base mesh for tissue region
runApplication snappyHexMesh -overwrite               # snappy hex mesh to chisel into curved shape

# GLAND MESHING 
cd ../gland/                                                    # move to gland folder
cleanCase
runApplication blockMesh                          # base mesh for gland region
runApplication pyFoamFromTemplate.py system/snappyHexMeshDict "{'x':0, 'y':0.035, 'z':0, 'r':0.005}"
runApplication snappyHexMesh -overwrite # snappy hex mesh to chisel into curved shape

# MERGE AND STITCH MUSCLE MESH ONTO GLAND              
runApplication mergeMeshes -overwrite . ../muscle/              # Merge muscle mesh onto the gland mesh and place it in Breast folder
runApplication stitchMesh -partial -toleranceDict toleranceDict -overwrite muscle_ext muscle_int  # partial stitch muscle patches per tolerance
cd 0
rm  meshPhi                           # remove meshPhi
cd ..                     
rm log.*                             # remove current merge and stitch logs
cd constant/polyMesh/                # move to constant polymesh to remove current zones
rm *Zones                            # remove all current zone files
rm meshModifiers                     # remove mesh modifiers

cd ../../                            # back to gland folder
# MERGE AND STITCH TISSUE MESH ONTO GLAND              
runApplication mergeMeshes -overwrite . ../tissue/              # Merge tissue mesh onto the gland mesh
runApplication stitchMesh -partial -toleranceDict toleranceDict -overwrite gland_ext gland_int   # partial stitch gland patches per tolerance
cd 0
rm  meshPhi                           # remove meshPhi
cd ..
rm log.*                             # remove current merge and stitch logs
cd constant/polyMesh/                # move to constant polymesh to remove current zones
rm *Zones                            # remove all current zone files
rm meshModifiers                     # remove mesh modifiers

cd ../../                            # back to gland folder
# MERGE AND STITCH TUMOR MESH ONTO GLAND              
runApplication mergeMeshes -overwrite . ../tumor/              # Merge tumor mesh onto the gland mesh
runApplication stitchMesh -partial -toleranceDict toleranceDict -overwrite tumor_ext tumor_int  # partial stitch tumor patches as per tolerance

# CHECK MESH AFTER STITCHING
runApplication checkMesh -constant -allGeometry -allTopology

# POST PROCESSING
echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll
runApplication touch all.OpenFOAM
