#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Muscle meshing
cd muscle/                                                      # move to muscle folder
cleanCase
runApplication blockMesh                          # base mesh for muscle region
runApplication snappyHexMesh -overwrite               # snappy hex mesh to chisel into curved shape


# GLAND MESHING 
cd ../Breast/                                                    # move to gland folder
cleanCase
runApplication blockMesh                          # base mesh for gland region
runApplication snappyHexMesh -overwrite # snappy hex mesh to chisel into curved shape


# MERGE AND STITCH MUSCLE MESH ONTO GLAND              
runApplication mergeMeshes -overwrite . ../muscle/              # Merge muscle mesh onto the gland mesh and place it in Breast folder
runApplication stitchMesh -partial -toleranceDict toleranceDict -overwrite muscle_ext muscle_int  # partial stitch muscle patches per tolerance
cd 0/
rm meshPhi                           # remove meshPhi
cd ..                     
rm log.*                             # remove current merge and stitch logs
cd constant/polyMesh/                # move to constant polymesh to remove current zones
rm *Zones                            # remove all current zone files
rm meshModifiers                     # remove mesh modifiers

cd ../../                            # back to Breast folder

runApplication checkMesh
