#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/tissue/polyMesh

find /home/shailesh/Niramai/Niramai_cases/with_subprocess/tissue/ -maxdepth 1 -mindepth 1 -not -name cleanT -not -name runT -not -name 0 -not -name constant -not -name system -exec rm -R {} \;
