#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh                          # base mesh for tissue region
runApplication snappyHexMesh -overwrite               # snappy hex mesh to chisel into curved shape


# CHECK MESH 
runApplication checkMesh -constant -allGeometry -allTopology

# Case report
runApplication pyFoamCaseReport.py --short-bc .

cd constant/
mv polyMesh tissue/polyMesh
cd ..

#for i in tissue
#do
#   runApplication -s $i  changeDictionary -region $i
#done

# RUN SOLVER ON SINGLE PROCESSOR
runApplication pyFoamPlotRunner.py --hardcopy --progress chtMultiRegionSimpleFoam 

# RUN REDO PLOT TO WRITE DATA FILES FROM PICKLED PLOTS
runApplication pyFoamRedoPlot.py --csv-files --pickle-file Gnuplotting.analyzed/pickledPlots

# RUN CASE REPORT TO CHECK THE BOUNDARY CONDITIONS
#runApplication pyFoamCaseReport.py --short-bc .


# POST PROCESSING
echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll
